name: RequestResponder
services:
    request-responder:
        container_name: request-responder
        image: mcr.microsoft.com/devcontainers/typescript-node:4-24-trixie
        volumes:
            - local-workspace:/workspace:cached
            - rr_node_modules:/workspace/node_modules
        command: 'sleep infinity'

volumes:
    rr_node_modules:
    local-workspace:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ../
